---
version: '2.1'
services:
  calibre:
    image: lscr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /Users/nigelalford/projects/tezos/foliomark-graphql/src/dataSources:/config
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
